services:
    mariadb:
        image: bitnami/mariadb:latest
        container_name: mariadb
        environment:
            - MARIADB_ROOT_PASSWORD=ChangeMe
            - MARIADB_USER=max
            - MARIADB_PASSWORD=ChangeMe
            - MARIADB_DATABASE=images_hosting
        networks:
            - laravel-network
        volumes:
            - mariadb_data:/bitnami/mariadb

    laravel-app:
        image: bitnami/laravel:latest
        container_name: test-case-laravel
        depends_on:
            - mariadb
        ports:
            - '8000:8000'
            - '3000:3000'
        environment:
            - DB_HOST=mariadb
            - DB_PORT=3306
            - DB_USERNAME=max
            - DB_PASSWORD=ChangeMe
            - DB_DATABASE=images_hosting
        networks:
            - laravel-network
        volumes:
            - ./:/app
        command: >
            bash -c "
              if [ ! -f .env ]; then
                cp .env.example .env;
              fi
              if [ ! -d vendor ]; then
                composer install;
              fi
              if [ ! -d node_modules ]; then
                npm install;
              fi
              npm run build;
              php artisan key:generate;
              php artisan migrate --force;
              php artisan serve --host=0.0.0.0 --port=8000
            "

networks:
    laravel-network:
        external: true
volumes:
    mariadb_data:
        name: mariadb_data
        external: true
